name: Convert Alpha Video

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg
        run: brew install ffmpeg

      - name: Download Video
        run: |
          curl -L "https://www.dropbox.com/scl/fi/8qk4c4b3m2imgoib7vk3i/video-transparente.mov?rlkey=t399115nk49nr3lhfxc4pmki7&st=jrudnaol&dl=0" -o video-trasparente.mov

      - name: Convert HEVC Alpha
        run: |
          ffmpeg -i video-trasparente.mov \
          -c:v hevc_videotoolbox \
          -alpha_quality 0.75 \
          -tag:v hvc1 \
          -pix_fmt bgra \
          video-alpha.mp4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-alpha
          path: video-alpha.mp4